runtime: nodejs10

instance_class: F2

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  DATABASE_NAME: 'acs-strapi-db'
  DATABASE_USERNAME: 'db-postgres'
  DATABASE_PASSWORD: 'kPecoecrPvkfrfG0'
  INSTANCE_CONNECTION_NAME: 'acs-strapi-295912:europe-west1:acs-strapi-db'

beta_settings:
  cloud_sql_instances: 'acs-strapi-295912:europe-west1:acs-strapi-db'
